# Form implementation generated from reading ui file 'AddAccDialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddAccDialog(object):
    def setupUi(self, AddAccDialog):
        AddAccDialog.setObjectName("AddAccDialog")
        AddAccDialog.resize(450, 330)
        AddAccDialog.setStyleSheet("background-color:rgb(40, 40, 40);")
        AddAccDialog.setModal(True)
        self.ScanQrButton = QtWidgets.QPushButton(AddAccDialog)
        self.ScanQrButton.setGeometry(QtCore.QRect(125, 30, 200, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ScanQrButton.setFont(font)
        self.ScanQrButton.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(1, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color: rgb(0, 255, 0);\n"
"color: rgb(0, 255, 0);\n"
"text-align:center;")
        self.ScanQrButton.setObjectName("ScanQrButton")
        self.QR_instructions = QtWidgets.QLabel(AddAccDialog)
        self.QR_instructions.setGeometry(QtCore.QRect(110, 110, 220, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.QR_instructions.setFont(font)
        self.QR_instructions.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.QR_instructions.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.QR_instructions.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.QR_instructions.setWordWrap(True)
        self.QR_instructions.setObjectName("QR_instructions")
        self.EnterManuallyButton = QtWidgets.QPushButton(AddAccDialog)
        self.EnterManuallyButton.setGeometry(QtCore.QRect(125, 210, 200, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.EnterManuallyButton.setFont(font)
        self.EnterManuallyButton.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(1, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color: rgb(0, 255, 0);\n"
"color: rgb(0, 255, 0);\n"
"text-align:center;")
        self.EnterManuallyButton.setObjectName("EnterManuallyButton")

        self.retranslateUi(AddAccDialog)
        QtCore.QMetaObject.connectSlotsByName(AddAccDialog)

    def retranslateUi(self, AddAccDialog):
        _translate = QtCore.QCoreApplication.translate
        AddAccDialog.setWindowTitle(_translate("AddAccDialog", "Add Account"))
        self.ScanQrButton.setText(_translate("AddAccDialog", "Scan QR"))
        self.QR_instructions.setText(_translate("AddAccDialog", "Make sure QR code is fully visible on main screen"))
        self.EnterManuallyButton.setText(_translate("AddAccDialog", "Enter Manually"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddAccDialog = QtWidgets.QDialog()
    ui = Ui_AddAccDialog()
    ui.setupUi(AddAccDialog)
    AddAccDialog.show()
    sys.exit(app.exec())
