# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ManualAddAcc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManualAddAccDialog(object):
    def setupUi(self, ManualAddAccDialog):
        ManualAddAccDialog.setObjectName("ManualAddAccDialog")
        ManualAddAccDialog.resize(498, 464)
        ManualAddAccDialog.setStyleSheet("background-color:rgb(40, 40, 40);")
        ManualAddAccDialog.setModal(True)
        self.QR_instructions = QtWidgets.QLabel(ManualAddAccDialog)
        self.QR_instructions.setGeometry(QtCore.QRect(50, 10, 401, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.QR_instructions.setFont(font)
        self.QR_instructions.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.QR_instructions.setTextFormat(QtCore.Qt.RichText)
        self.QR_instructions.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.QR_instructions.setWordWrap(True)
        self.QR_instructions.setObjectName("QR_instructions")
        self.IssuerlineEdit = QtWidgets.QLineEdit(ManualAddAccDialog)
        self.IssuerlineEdit.setGeometry(QtCore.QRect(50, 130, 411, 25))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.IssuerlineEdit.setFont(font)
        self.IssuerlineEdit.setStyleSheet("color: rgb(0, 255, 0);")
        self.IssuerlineEdit.setObjectName("IssuerlineEdit")
        self.IssuerLabel = QtWidgets.QLabel(ManualAddAccDialog)
        self.IssuerLabel.setGeometry(QtCore.QRect(50, 100, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.IssuerLabel.setFont(font)
        self.IssuerLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.IssuerLabel.setTextFormat(QtCore.Qt.RichText)
        self.IssuerLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.IssuerLabel.setWordWrap(True)
        self.IssuerLabel.setObjectName("IssuerLabel")
        self.AccNameLabel = QtWidgets.QLabel(ManualAddAccDialog)
        self.AccNameLabel.setGeometry(QtCore.QRect(50, 175, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.AccNameLabel.setFont(font)
        self.AccNameLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.AccNameLabel.setTextFormat(QtCore.Qt.RichText)
        self.AccNameLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.AccNameLabel.setWordWrap(True)
        self.AccNameLabel.setObjectName("AccNameLabel")
        self.SecretKeyLabel = QtWidgets.QLabel(ManualAddAccDialog)
        self.SecretKeyLabel.setGeometry(QtCore.QRect(50, 245, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.SecretKeyLabel.setFont(font)
        self.SecretKeyLabel.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.SecretKeyLabel.setTextFormat(QtCore.Qt.RichText)
        self.SecretKeyLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SecretKeyLabel.setWordWrap(True)
        self.SecretKeyLabel.setObjectName("SecretKeyLabel")
        self.AddButton = QtWidgets.QPushButton(ManualAddAccDialog)
        self.AddButton.setGeometry(QtCore.QRect(50, 330, 111, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.AddButton.setFont(font)
        self.AddButton.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(1, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color: rgb(0, 255, 0);\n"
"color: rgb(0, 255, 0);\n"
"text-align:center;")
        self.AddButton.setObjectName("AddButton")
        self.AccNamelineEdit = QtWidgets.QLineEdit(ManualAddAccDialog)
        self.AccNamelineEdit.setGeometry(QtCore.QRect(50, 205, 411, 25))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.AccNamelineEdit.setFont(font)
        self.AccNamelineEdit.setStyleSheet("color: rgb(0, 255, 0);")
        self.AccNamelineEdit.setObjectName("AccNamelineEdit")
        self.SecretlineEdit = QtWidgets.QLineEdit(ManualAddAccDialog)
        self.SecretlineEdit.setGeometry(QtCore.QRect(50, 275, 411, 25))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.SecretlineEdit.setFont(font)
        self.SecretlineEdit.setStyleSheet("color: rgb(0, 255, 0);")
        self.SecretlineEdit.setObjectName("SecretlineEdit")

        self.retranslateUi(ManualAddAccDialog)
        QtCore.QMetaObject.connectSlotsByName(ManualAddAccDialog)

    def retranslateUi(self, ManualAddAccDialog):
        _translate = QtCore.QCoreApplication.translate
        ManualAddAccDialog.setWindowTitle(_translate("ManualAddAccDialog", "Add Account"))
        self.QR_instructions.setText(_translate("ManualAddAccDialog", "<html><head/><body><p>Add Account</p><p>Use manual entry if there is no QR code available.</p></body></html>"))
        self.IssuerLabel.setText(_translate("ManualAddAccDialog", "<html><head/><body><p>Issuer</p></body></html>"))
        self.AccNameLabel.setText(_translate("ManualAddAccDialog", "<html><head/><body><p>Account name</p></body></html>"))
        self.SecretKeyLabel.setText(_translate("ManualAddAccDialog", "<html><head/><body><p>Secret key</p></body></html>"))
        self.AddButton.setText(_translate("ManualAddAccDialog", "ADD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ManualAddAccDialog = QtWidgets.QDialog()
    ui = Ui_ManualAddAccDialog()
    ui.setupUi(ManualAddAccDialog)
    ManualAddAccDialog.show()
    sys.exit(app.exec_())
