# Form implementation generated from reading ui file 'passphraseDialog.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PassphraseDialog(object):
    def setupUi(self, PassphraseDialog):
        PassphraseDialog.setObjectName("PassphraseDialog")
        PassphraseDialog.resize(902, 163)
        PassphraseDialog.setStyleSheet("background-color:rgb(40, 40, 40);")
        PassphraseDialog.setModal(True)
        self.passphrase = QtWidgets.QLabel(PassphraseDialog)
        self.passphrase.setGeometry(QtCore.QRect(50, 10, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.passphrase.setFont(font)
        self.passphrase.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.passphrase.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.passphrase.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.passphrase.setWordWrap(True)
        self.passphrase.setObjectName("passphrase")
        self.passphraseLineEdit = QtWidgets.QLineEdit(PassphraseDialog)
        self.passphraseLineEdit.setGeometry(QtCore.QRect(50, 40, 731, 25))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.passphraseLineEdit.setFont(font)
        self.passphraseLineEdit.setStyleSheet("color: rgb(0, 255, 0);")
        self.passphraseLineEdit.setObjectName("passphraseLineEdit")
        self.EnterButton = QtWidgets.QPushButton(PassphraseDialog)
        self.EnterButton.setGeometry(QtCore.QRect(50, 80, 111, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.EnterButton.setFont(font)
        self.EnterButton.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(1, 0, 0);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color: rgb(0, 255, 0);\n"
"color: rgb(0, 255, 0);\n"
"text-align:center;")
        self.EnterButton.setObjectName("EnterButton")

        self.retranslateUi(PassphraseDialog)
        QtCore.QMetaObject.connectSlotsByName(PassphraseDialog)

    def retranslateUi(self, PassphraseDialog):
        _translate = QtCore.QCoreApplication.translate
        PassphraseDialog.setWindowTitle(_translate("PassphraseDialog", "Enter Passphrase"))
        self.passphrase.setText(_translate("PassphraseDialog", "<html><head/><body><p>Passphrase:</p></body></html>"))
        self.EnterButton.setText(_translate("PassphraseDialog", "Enter"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PassphraseDialog = QtWidgets.QDialog()
    ui = Ui_PassphraseDialog()
    ui.setupUi(PassphraseDialog)
    PassphraseDialog.show()
    sys.exit(app.exec())
