# Form implementation generated from reading ui file 'PinUi.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(576, 634)
        Dialog.setStyleSheet("background-color: rgb(1, 0, 0);")
        Dialog.setModal(True)
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(110, 140, 101, 91))
        self.pushButton_7.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(103, 103, 103);\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color: black;")
        self.pushButton_7.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("circle-32.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(110, 250, 101, 91))
        self.pushButton_4.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(103, 103, 103);\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color: black;")
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_1 = QtWidgets.QPushButton(Dialog)
        self.pushButton_1.setGeometry(QtCore.QRect(110, 360, 101, 91))
        self.pushButton_1.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(103, 103, 103);\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color: black;")
        self.pushButton_1.setText("")
        self.pushButton_1.setIcon(icon)
        self.pushButton_1.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(240, 140, 101, 91))
        self.pushButton_8.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(103, 103, 103);\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color: black;")
        self.pushButton_8.setIcon(icon)
        self.pushButton_8.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(240, 250, 101, 91))
        self.pushButton_5.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(103, 103, 103);\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color: black;")
        self.pushButton_5.setText("")
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 360, 101, 91))
        self.pushButton_2.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(103, 103, 103);\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color: black;")
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(370, 140, 101, 91))
        self.pushButton_9.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(103, 103, 103);\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color: black;")
        self.pushButton_9.setIcon(icon)
        self.pushButton_9.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(370, 250, 101, 91))
        self.pushButton_6.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(103, 103, 103);\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color: black;")
        self.pushButton_6.setText("")
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(370, 360, 101, 91))
        self.pushButton_3.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(103, 103, 103);\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color: black;")
        self.pushButton_3.setText("")
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 10, 441, 121))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.pbUnlock = QtWidgets.QPushButton(Dialog)
        self.pbUnlock.setGeometry(QtCore.QRect(65, 550, 440, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pbUnlock.setFont(font)
        self.pbUnlock.setStyleSheet("background-color: rgb(184, 155, 104);\n"
"border-radius: 10px;\n"
"color: rgb(255, 255,255);")
        self.pbUnlock.setObjectName("pbUnlock")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(65, 470, 440, 60))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(1, 0, 0);\n"
"border-radius: 10px;\n"
"color: rgb(255, 255,255);\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color: rgb(103, 103, 103);")
        self.lineEdit.setMaxLength(10)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "PIN Entry"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:24pt; font-weight:600;\">Enter Your PIN</span></p><p><span style=\" font-size:18pt; font-weight:600;\">Use PIN layout shown on your device to find the </span></p><p><span style=\" font-size:18pt; font-weight:600;\">location to press on the PIN pad.</span></p></body></html>"))
        self.pbUnlock.setText(_translate("Dialog", "Unlock"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
