# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'remaccdialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RemAccDialog(object):
    def setupUi(self, RemAccDialog):
        RemAccDialog.setObjectName("RemAccDialog")
        RemAccDialog.resize(465, 388)
        RemAccDialog.setStyleSheet("background-color: rgb(1, 0, 0);")
        RemAccDialog.setModal(True)
        self.RemAccButton_1 = QtWidgets.QPushButton(RemAccDialog)
        self.RemAccButton_1.setGeometry(QtCore.QRect(50, 80, 350, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.RemAccButton_1.setFont(font)
        self.RemAccButton_1.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(1, 0, 0);\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color: black;\n"
"color: rgb(0, 255, 0);\n"
"text-align:left;")
        self.RemAccButton_1.setText("")
        self.RemAccButton_1.setObjectName("RemAccButton_1")
        self.RemoveAccButtonGroup = QtWidgets.QButtonGroup(RemAccDialog)
        self.RemoveAccButtonGroup.setObjectName("RemoveAccButtonGroup")
        self.RemoveAccButtonGroup.addButton(self.RemAccButton_1)
        self.AccountList = QtWidgets.QLabel(RemAccDialog)
        self.AccountList.setGeometry(QtCore.QRect(50, 20, 130, 45))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.AccountList.setFont(font)
        self.AccountList.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.AccountList.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.AccountList.setObjectName("AccountList")
        self.AccountList_2 = QtWidgets.QLabel(RemAccDialog)
        self.AccountList_2.setGeometry(QtCore.QRect(195, 20, 220, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.AccountList_2.setFont(font)
        self.AccountList_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.AccountList_2.setTextFormat(QtCore.Qt.RichText)
        self.AccountList_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.AccountList_2.setWordWrap(True)
        self.AccountList_2.setObjectName("AccountList_2")
        self.RemAccButton_2 = QtWidgets.QPushButton(RemAccDialog)
        self.RemAccButton_2.setGeometry(QtCore.QRect(50, 140, 350, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.RemAccButton_2.setFont(font)
        self.RemAccButton_2.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(1, 0, 0);\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color: black;\n"
"color: rgb(0, 255, 0);\n"
"text-align:left;")
        self.RemAccButton_2.setText("")
        self.RemAccButton_2.setObjectName("RemAccButton_2")
        self.RemoveAccButtonGroup.addButton(self.RemAccButton_2)
        self.RemAccButton_3 = QtWidgets.QPushButton(RemAccDialog)
        self.RemAccButton_3.setGeometry(QtCore.QRect(50, 200, 350, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.RemAccButton_3.setFont(font)
        self.RemAccButton_3.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(1, 0, 0);\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color: black;\n"
"color: rgb(0, 255, 0);\n"
"text-align:left;")
        self.RemAccButton_3.setText("")
        self.RemAccButton_3.setObjectName("RemAccButton_3")
        self.RemoveAccButtonGroup.addButton(self.RemAccButton_3)
        self.RemAccButton_4 = QtWidgets.QPushButton(RemAccDialog)
        self.RemAccButton_4.setGeometry(QtCore.QRect(50, 260, 350, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.RemAccButton_4.setFont(font)
        self.RemAccButton_4.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(1, 0, 0);\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color: black;\n"
"color: rgb(0, 255, 0);\n"
"text-align:left;")
        self.RemAccButton_4.setText("")
        self.RemAccButton_4.setObjectName("RemAccButton_4")
        self.RemoveAccButtonGroup.addButton(self.RemAccButton_4)
        self.RemAccButton_5 = QtWidgets.QPushButton(RemAccDialog)
        self.RemAccButton_5.setGeometry(QtCore.QRect(50, 320, 350, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.RemAccButton_5.setFont(font)
        self.RemAccButton_5.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(1, 0, 0);\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color: black;\n"
"color: rgb(0, 255, 0);\n"
"text-align:left;")
        self.RemAccButton_5.setText("")
        self.RemAccButton_5.setObjectName("RemAccButton_5")
        self.RemoveAccButtonGroup.addButton(self.RemAccButton_5)

        self.retranslateUi(RemAccDialog)
        QtCore.QMetaObject.connectSlotsByName(RemAccDialog)

    def retranslateUi(self, RemAccDialog):
        _translate = QtCore.QCoreApplication.translate
        RemAccDialog.setWindowTitle(_translate("RemAccDialog", "Remove Account"))
        self.AccountList.setText(_translate("RemAccDialog", "Accounts"))
        self.AccountList_2.setText(_translate("RemAccDialog", "Click on account to PERMANENTLY remove"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RemAccDialog = QtWidgets.QDialog()
    ui = Ui_RemAccDialog()
    ui.setupUi(RemAccDialog)
    RemAccDialog.show()
    sys.exit(app.exec_())
