"""The firmware token table is generated BY THIS REPOSITORY.

lib/firmware/CMakeLists.txt in keepkey-firmware builds `ethereum_tokens.def`
and `uniswap_tokens.def` by running

    python3 deps/python-keepkey/keepkeylib/eth/ethereum_tokens.py <out>.def
    python3 deps/python-keepkey/keepkeylib/eth/uniswap_tokens.py  <out>.def

and `kkfirmware` depends on that target. So a change in this repository CAN
break the firmware C++ build: if either generator crashes, emits a malformed
X(...) row, or emits an address that is not 20 bytes, the firmware does not
compile -- and `tokens[]` is what unittests/firmware/coins.cpp reads.

.circleci/config.yml used to run the firmware's own C++ suite here and gated
this job on it. That gate was removed. This module is the replacement Copilot
asked for on that change: an equivalent generator/firmware contract gate that
lives where the change originates, runs in seconds, and does not fail this
repository for unrelated firmware C++ churn.

It deliberately asserts the BUILD contract (the generators run and emit a
well-formed, budget-conforming table), not the token SELECTION, which is
policy and moves.
"""

import ast
import importlib
import os
import re
import subprocess
import sys
import tempfile
import unittest

_HERE = os.path.dirname(os.path.abspath(__file__))
_PYKEEPKEY = os.path.dirname(_HERE)
_ETH = os.path.join(_PYKEEPKEY, 'keepkeylib', 'eth')

# X(chain_id, "<20 escaped bytes>", " SYMBOL", decimals) // comment
#
# END-ANCHORED. Without the trailing anchor a row like
#   X(1, "...", " AAA", 18) ;;; garbage
# matches on its valid prefix, so this gate would pass a line the firmware
# preprocessor cannot consume -- which is the one thing it exists to catch.
# Only whitespace and a // comment may follow the closing paren.
_ROW = re.compile(
    r'^X\((\d+),\s*"((?:[^"\\]|\\.)*)",\s*"\s*([^"]+)",\s*(\d+)\)'
    r'\s*(?://.*)?$')

GENERATORS = (
    ('ethereum_tokens.py', 'BUDGET_ETHEREUM_LISTS'),
    ('uniswap_tokens.py', 'BUDGET_UNISWAP_LIST'),
)


def _vetted_source_present():
    """The ethereum-lists submodule must be checked out for the eth generator."""
    return os.path.isdir(os.path.join(_ETH, 'ethereum-lists', 'src', 'tokens'))


class TestTokenTableGenerators(unittest.TestCase):

    def test_ethereum_tokens_missing_source_fails_closed(self):
        """A non-recursive checkout must stop the firmware build, not emit 0 rows."""
        module = importlib.import_module('keepkeylib.eth.ethereum_tokens')
        original_here = module.HERE
        with tempfile.TemporaryDirectory() as tmp:
            module.HERE = tmp
            try:
                with self.assertRaisesRegex(
                        RuntimeError, 'ethereum-lists token source is missing'):
                    module.ETHTokenTable().build()
            finally:
                module.HERE = original_here

    def _run(self, script):
        """Run one generator into a temp file and return its rows."""
        with tempfile.TemporaryDirectory() as tmp:
            out = os.path.join(tmp, 'out.def')
            proc = subprocess.run(
                [sys.executable, os.path.join(_ETH, script), out],
                stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                universal_newlines=True, cwd=_PYKEEPKEY)
            self.assertEqual(
                proc.returncode, 0,
                '%s exited %d -- the firmware build runs this exact command '
                'and would fail here.\nstdout: %s\nstderr: %s'
                % (script, proc.returncode, proc.stdout[-2000:],
                   proc.stderr[-2000:]))
            self.assertTrue(os.path.isfile(out),
                            '%s produced no output file' % script)
            with open(out) as f:
                text = f.read()
        return text, (proc.stdout or '') + (proc.stderr or '')

    def _rows(self, text, script):
        rows = []
        for line in text.splitlines():
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            match = _ROW.match(line)
            self.assertIsNotNone(
                match,
                '%s emitted a line the firmware preprocessor cannot consume: %r'
                % (script, line[:120]))
            chain_id, address, symbol, decimals = match.groups()
            rows.append((int(chain_id), address, symbol.strip(), int(decimals)))
        return rows

    def _check(self, script, budget_name):
        if script == 'ethereum_tokens.py' and not _vetted_source_present():
            self.skipTest('keepkeylib/eth/ethereum-lists submodule not checked out')
        from keepkeylib.eth import token_policy

        text, log = self._run(script)
        rows = self._rows(text, script)
        self.assertTrue(rows, '%s emitted an empty table' % script)

        budget = getattr(token_policy, budget_name)
        self.assertTrue(
            len(rows) <= budget,
            '%s emitted %d rows, over its %s budget of %d -- this symbol is '
            'the largest read-only object in the ARM image'
            % (script, len(rows), budget_name, budget))

        # The generator reports 'N of M kept (budget B)'. Checking N against
        # min(M, B) catches SHRINKAGE too: a change that silently drops most
        # candidates still respects the ceiling, so `<= budget` alone would
        # let the device's token table quietly collapse.
        kept = re.search(r'(\d+) of (\d+) kept \(budget (\d+)\)', log)
        self.assertIsNotNone(
            kept, '%s no longer reports its keep/candidate counts: %r'
                  % (script, log[-500:]))
        n_kept, n_candidates, reported_budget = (int(g) for g in kept.groups())
        self.assertEqual(reported_budget, budget,
                         '%s reports a budget that is not %s' % (script, budget_name))
        self.assertEqual(
            n_kept, min(n_candidates, budget),
            '%s kept %d of %d candidates against a budget of %d -- it must '
            'fill the budget when the source has the entries'
            % (script, n_kept, n_candidates, budget))
        self.assertEqual(
            len(rows), n_kept,
            '%s reported %d kept but emitted %d rows'
            % (script, n_kept, len(rows)))

        for chain_id, address, symbol, decimals in rows:
            # The C string is 20 raw bytes; anything else silently shifts the
            # packed token struct the firmware reads.
            raw = ast.literal_eval('b"%s"' % address)
            self.assertEqual(
                len(raw), 20,
                '%s: %s on chain %d has a %d-byte address, not 20'
                % (script, symbol, chain_id, len(raw)))
            self.assertTrue(
                0 <= decimals <= 32,
                '%s: %s has implausible decimals %d' % (script, symbol, decimals))
            self.assertTrue(
                symbol and '"' not in symbol,
                '%s: unusable symbol %r' % (script, symbol))

    def test_ethereum_tokens_generator_builds_a_valid_table(self):
        self._check('ethereum_tokens.py', 'BUDGET_ETHEREUM_LISTS')

    def test_ethereum_tokens_closes_the_x_macro(self):
        """ethereum_tokens.def is #included after a #define X; leaving the
        macro defined leaks it into the next translation unit."""
        if not _vetted_source_present():
            self.skipTest('keepkeylib/eth/ethereum-lists submodule not checked out')
        self.assertIn('#undef X', self._run('ethereum_tokens.py')[0])

    def test_uniswap_tokens_generator_builds_a_valid_table(self):
        self._check('uniswap_tokens.py', 'BUDGET_UNISWAP_LIST')

    def test_generators_are_deterministic(self):
        """The firmware build compares digests to decide whether to rewrite the
        .def; a non-deterministic generator would churn the table every build."""
        for script, _ in GENERATORS:
            if script == 'ethereum_tokens.py' and not _vetted_source_present():
                continue
            self.assertEqual(self._run(script)[0], self._run(script)[0],
                             '%s is not deterministic' % script)


if __name__ == '__main__':
    unittest.main()
