# Real-world EIP-712 documents must sign.
#
# eip712_corpus.json holds one document per protocol (Permit2, UniswapX,
# Seaport, LooksRare, Blur, 1inch, CoW, 0x, Safe, EIP-2612/DAI, Hyperliquid,
# Polymarket, Compound, Aave, dYdX, Across, Snapshot, eth-sig-util), written
# from the type strings in each protocol's own source ("source" in each
# entry). It is generated by unittests/firmware/eip712_corpus_gen.py in the
# firmware repository, whose "expected" hashes were computed by a reference
# encoder and cross-checked against @metamask/eth-sig-util and ethers.
#
# Every document must be ACCEPTED: its hashes must equal both the embedded
# values and this suite's own independent encoder, its signature must
# recover to the device's address, and the final screen must name the whole
# primary type.

import json
import os
import unittest

import common
import oled_text
import test_msg_eip712_streaming as streaming
from keepkeylib import messages_ethereum_pb2 as eth
from keepkeylib import types_pb2 as types

CORPUS = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                      'eip712_corpus.json')


def load_corpus():
    with open(CORPUS) as f:
        return json.load(f)


class TestEip712CorpusReference(unittest.TestCase):

    def test_embedded_hashes_match_the_independent_encoder(self):
        """The suite's own encoder agrees with the generator's values."""
        for entry in load_corpus():
            with self.subTest(entry['id']):
                domain, message, digest = \
                    streaming.reference_eip712_hashes(entry['doc'])
                self.assertEqual(domain.hex(),
                                 entry['expected']['domain_separator'])
                self.assertEqual(message.hex(),
                                 entry['expected']['message_hash'])
                self.assertEqual(digest.hex(), entry['expected']['digest'])


class TestMsgEip712Corpus(common.KeepKeyTest):

    # The device-driven walk from the streaming suite; borrowed, not
    # inherited, so its tests do not run twice.
    _walk = streaming.TestMsgEip712Streaming._walk

    def setUp(self):
        super(TestMsgEip712Corpus, self).setUp()
        self.requires_firmware("7.15.0")
        self.requires_fullFeature()
        self.requires_structured_eip712()
        self.setup_mnemonic_nopin_nopassphrase()
        self.client.apply_policy('AdvancedMode', 0)
        self.client.reset_screenshots()

    def test_every_real_world_document_signs(self):
        address = self.client.ethereum_get_address(streaming.PATH)
        for entry in load_corpus():
            with self.subTest(entry['id']):
                doc = entry['doc']
                resp = self._walk(doc, max_steps=2000)
                self.assertIsInstance(resp, eth.EthereumTypedDataSignature,
                                      getattr(resp, 'message', resp))
                self.assertEqual(resp.domain_separator_hash.hex(),
                                 entry['expected']['domain_separator'])
                self.assertEqual(resp.message_hash.hex(),
                                 entry['expected']['message_hash'])
                digest = bytes.fromhex(entry['expected']['digest'])
                self.assertEqual(
                    streaming.recover_signer(resp.signature, digest).hex(),
                    address.hex())
                # The final screen (and its continuation pages) names the
                # whole primary type, however long.
                codes = [code for code, _ in self.frames]
                self.assertEqual(codes.count(types.ButtonRequest_SignTx), 1)
                final = codes.index(types.ButtonRequest_SignTx)
                self.assertIsNotNone(oled_text.find_text(
                    [layout for _, layout in self.frames[final:]],
                    'Sign ' + doc['primaryType']))


if __name__ == '__main__':
    unittest.main()
