# Zcash Orchard shielded transaction tests.
#
# Tests FVK derivation (ZcashGetOrchardFVK) against reference values
# computed by the orchard Rust crate from known BIP-39 seeds.
#
# These tests catch:
#   - to_base / to_scalar reduction bugs (nk, rivk, ask out of field range)
#   - ask negation bugs (ak sign bit must be 0)
#   - Full FVK consistency (ak || nk || rivk must be accepted by orchard crate)
#   - Determinism (same seed → same FVK every time)

import unittest
import common
import binascii

# Pallas curve constants
PALLAS_P = 0x40000000000000000000000000000000224698fc094cf91b992d30ed00000001
PALLAS_Q = 0x40000000000000000000000000000000224698fc0994a8dd8c46eb2100000001

# Reference FVK test vectors for mnemonic "all all all ... all" (12x "all")
# Generated by orchard Rust crate (authoritative ZIP-32 implementation)
# Seed (BIP-39 PBKDF2, no passphrase):
#   c76c4ac4f4e4a00d6b274d5c39c700bb4a7ddc04fbc6f78e85ca75007b5b495f
#   74a9043eeb77bdd53aa6fc3a0e31462270316fa04b8c19114c8798706cd02ac8
REFERENCE_FVK_ALL_MNEMONIC = {
    'ak':   '057ab051d4fbb0205d28648bacbc6471b533476c27beca33e5b9f511d855672b',
    'nk':   '34a35a0bda50273b0319afa7a70f86b6b162eb311d263d8f6321def00228ba25',
    'rivk': '46bd2bd5e6eca5ef03e18cd76595519ea96706c5826a93ba4dca947d711a7c0a',
}


def bytes_to_int_le(b):
    """Convert LE bytes to integer."""
    return int.from_bytes(b, 'little')


class TestZcashOrchardFVK(common.KeepKeyTest):
    """Test Zcash Orchard Full Viewing Key derivation."""

    def test_fvk_field_ranges(self):
        """FVK components must be in valid field ranges.

        - ak: valid Pallas point (sign bit must be 0, i.e. canonical ỹ = 0)
        - nk: valid Pallas base field element (< p)
        - rivk: valid Pallas scalar field element (< q)
        """
        self.setup_mnemonic_allallall()

        # ZIP-32 Orchard path: m/32'/133'/0'
        address_n = [0x80000000 + 32, 0x80000000 + 133, 0x80000000]
        resp = self.client.zcash_get_orchard_fvk(address_n=address_n, account=0)

        ak = resp.ak
        nk = resp.nk
        rivk = resp.rivk

        self.assertTrue(len(ak) == 32, "ak must be 32 bytes")
        self.assertTrue(len(nk) == 32, "nk must be 32 bytes")
        self.assertTrue(len(rivk) == 32, "rivk must be 32 bytes")

        # ak sign bit must be 0 (canonical form per Zcash spec § 4.2.3)
        self.assertTrue(ak[31] & 0x80 == 0, "ak sign bit must be 0 (canonical form), got high byte 0x%02x" % ak[31])

        # nk must be < Pallas base field prime p
        nk_int = bytes_to_int_le(nk)
        self.assertTrue(nk_int < PALLAS_P, "nk must be < Pallas prime p, got 0x%064x" % nk_int)

        # rivk must be < Pallas scalar field order q
        rivk_int = bytes_to_int_le(rivk)
        self.assertTrue(rivk_int < PALLAS_Q, "rivk must be < Pallas order q, got 0x%064x" % rivk_int)

    def test_fvk_reference_vectors(self):
        """FVK must match reference values from the orchard Rust crate.

        Uses mnemonic "all all all all all all all all all all all all"
        with account 0, which is the standard test seed.
        Firmware now uses storage_getSeed() for real BIP-39 seed.
        """
        self.setup_mnemonic_allallall()

        address_n = [0x80000000 + 32, 0x80000000 + 133, 0x80000000]
        resp = self.client.zcash_get_orchard_fvk(address_n=address_n, account=0)

        ak_hex = binascii.hexlify(resp.ak).decode()
        nk_hex = binascii.hexlify(resp.nk).decode()
        rivk_hex = binascii.hexlify(resp.rivk).decode()

        self.assertTrue(ak_hex == REFERENCE_FVK_ALL_MNEMONIC['ak'], "ak mismatch:\n  got:      %s\n  expected: %s" % (ak_hex, REFERENCE_FVK_ALL_MNEMONIC['ak']))
        self.assertTrue(nk_hex == REFERENCE_FVK_ALL_MNEMONIC['nk'], "nk mismatch:\n  got:      %s\n  expected: %s" % (nk_hex, REFERENCE_FVK_ALL_MNEMONIC['nk']))
        self.assertTrue(rivk_hex == REFERENCE_FVK_ALL_MNEMONIC['rivk'], "rivk mismatch:\n  got:      %s\n  expected: %s" % (rivk_hex, REFERENCE_FVK_ALL_MNEMONIC['rivk']))

    def test_fvk_consistency_across_calls(self):
        """Multiple FVK requests with the same account must return identical keys."""
        self.setup_mnemonic_allallall()

        address_n = [0x80000000 + 32, 0x80000000 + 133, 0x80000000]

        resp1 = self.client.zcash_get_orchard_fvk(address_n=address_n, account=0)
        resp2 = self.client.zcash_get_orchard_fvk(address_n=address_n, account=0)

        self.assertTrue(resp1.ak == resp2.ak, "ak must be deterministic")
        self.assertTrue(resp1.nk == resp2.nk, "nk must be deterministic")
        self.assertTrue(resp1.rivk == resp2.rivk, "rivk must be deterministic")

    def test_fvk_different_accounts(self):
        """Different account indices must produce different FVKs."""
        self.setup_mnemonic_allallall()

        address_n_0 = [0x80000000 + 32, 0x80000000 + 133, 0x80000000]
        address_n_1 = [0x80000000 + 32, 0x80000000 + 133, 0x80000001]

        resp0 = self.client.zcash_get_orchard_fvk(address_n=address_n_0, account=0)
        resp1 = self.client.zcash_get_orchard_fvk(address_n=address_n_1, account=1)

        self.assertTrue(resp0.ak != resp1.ak, "Different accounts must produce different ak")

    def test_fvk_abandon_mnemonic(self):
        """FVK field ranges must be valid for a different mnemonic too.

        Uses "abandon" mnemonic to test a second seed.
        """
        self.setup_mnemonic_abandon()

        address_n = [0x80000000 + 32, 0x80000000 + 133, 0x80000000]
        resp = self.client.zcash_get_orchard_fvk(address_n=address_n, account=0)

        # Check field ranges (not reference values — just validity)
        self.assertTrue(resp.ak[31] & 0x80 == 0, "ak sign bit must be 0 for abandon mnemonic")
        nk_int = bytes_to_int_le(resp.nk)
        self.assertTrue(nk_int < PALLAS_P, "nk must be < p for abandon mnemonic")
        rivk_int = bytes_to_int_le(resp.rivk)
        self.assertTrue(rivk_int < PALLAS_Q, "rivk must be < q for abandon mnemonic")


if __name__ == '__main__':
    unittest.main()
