# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages-mayachain.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import types_pb2 as types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages-mayachain.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x18messages-mayachain.proto\x1a\x0btypes.proto\"O\n\x13MayachainGetAddress\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x14\n\x0cshow_display\x18\x02 \x01(\x08\x12\x0f\n\x07testnet\x18\x03 \x01(\x08\"#\n\x10MayachainAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\xbb\x01\n\x0fMayachainSignTx\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x1a\n\x0e\x61\x63\x63ount_number\x18\x02 \x01(\x04\x42\x02\x30\x01\x12\x10\n\x08\x63hain_id\x18\x03 \x01(\t\x12\x12\n\nfee_amount\x18\x04 \x01(\r\x12\x0b\n\x03gas\x18\x05 \x01(\r\x12\x0c\n\x04memo\x18\x06 \x01(\t\x12\x14\n\x08sequence\x18\x07 \x01(\x04\x42\x02\x30\x01\x12\x11\n\tmsg_count\x18\x08 \x01(\r\x12\x0f\n\x07testnet\x18\t \x01(\x08\"\x15\n\x13MayachainMsgRequest\"Y\n\x0fMayachainMsgAck\x12\x1f\n\x04send\x18\x01 \x01(\x0b\x32\x11.MayachainMsgSend\x12%\n\x07\x64\x65posit\x18\x02 \x01(\x0b\x32\x14.MayachainMsgDeposit\"\x8f\x01\n\x10MayachainMsgSend\x12\x14\n\x0c\x66rom_address\x18\x06 \x01(\t\x12\x12\n\nto_address\x18\x07 \x01(\t\x12\x12\n\x06\x61mount\x18\x08 \x01(\x04\x42\x02\x30\x01\x12(\n\x0c\x61\x64\x64ress_type\x18\t \x01(\x0e\x32\x12.OutputAddressType\x12\r\n\x05\x64\x65nom\x18\x0b \x01(\tJ\x04\x08\n\x10\x0b\"V\n\x13MayachainMsgDeposit\x12\r\n\x05\x61sset\x18\x01 \x01(\t\x12\x12\n\x06\x61mount\x18\x02 \x01(\x04\x42\x02\x30\x01\x12\x0c\n\x04memo\x18\x03 \x01(\t\x12\x0e\n\x06signer\x18\x04 \x01(\t\":\n\x11MayachainSignedTx\x12\x12\n\npublic_key\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x42\x35\n\x1a\x63om.keepkey.deviceprotocolB\x17KeepKeyMessageMayachain')
  ,
  dependencies=[types__pb2.DESCRIPTOR,])




_MAYACHAINGETADDRESS = _descriptor.Descriptor(
  name='MayachainGetAddress',
  full_name='MayachainGetAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address_n', full_name='MayachainGetAddress.address_n', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='show_display', full_name='MayachainGetAddress.show_display', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='testnet', full_name='MayachainGetAddress.testnet', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=120,
)


_MAYACHAINADDRESS = _descriptor.Descriptor(
  name='MayachainAddress',
  full_name='MayachainAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='MayachainAddress.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=157,
)


_MAYACHAINSIGNTX = _descriptor.Descriptor(
  name='MayachainSignTx',
  full_name='MayachainSignTx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address_n', full_name='MayachainSignTx.address_n', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account_number', full_name='MayachainSignTx.account_number', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('0\001')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chain_id', full_name='MayachainSignTx.chain_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fee_amount', full_name='MayachainSignTx.fee_amount', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gas', full_name='MayachainSignTx.gas', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memo', full_name='MayachainSignTx.memo', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='MayachainSignTx.sequence', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('0\001')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_count', full_name='MayachainSignTx.msg_count', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='testnet', full_name='MayachainSignTx.testnet', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=160,
  serialized_end=347,
)


_MAYACHAINMSGREQUEST = _descriptor.Descriptor(
  name='MayachainMsgRequest',
  full_name='MayachainMsgRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=349,
  serialized_end=370,
)


_MAYACHAINMSGACK = _descriptor.Descriptor(
  name='MayachainMsgAck',
  full_name='MayachainMsgAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='send', full_name='MayachainMsgAck.send', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deposit', full_name='MayachainMsgAck.deposit', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=461,
)


_MAYACHAINMSGSEND = _descriptor.Descriptor(
  name='MayachainMsgSend',
  full_name='MayachainMsgSend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from_address', full_name='MayachainMsgSend.from_address', index=0,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_address', full_name='MayachainMsgSend.to_address', index=1,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='MayachainMsgSend.amount', index=2,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('0\001')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address_type', full_name='MayachainMsgSend.address_type', index=3,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='denom', full_name='MayachainMsgSend.denom', index=4,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=464,
  serialized_end=607,
)


_MAYACHAINMSGDEPOSIT = _descriptor.Descriptor(
  name='MayachainMsgDeposit',
  full_name='MayachainMsgDeposit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='asset', full_name='MayachainMsgDeposit.asset', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='MayachainMsgDeposit.amount', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('0\001')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memo', full_name='MayachainMsgDeposit.memo', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signer', full_name='MayachainMsgDeposit.signer', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=609,
  serialized_end=695,
)


_MAYACHAINSIGNEDTX = _descriptor.Descriptor(
  name='MayachainSignedTx',
  full_name='MayachainSignedTx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='public_key', full_name='MayachainSignedTx.public_key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='MayachainSignedTx.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=697,
  serialized_end=755,
)

_MAYACHAINMSGACK.fields_by_name['send'].message_type = _MAYACHAINMSGSEND
_MAYACHAINMSGACK.fields_by_name['deposit'].message_type = _MAYACHAINMSGDEPOSIT
_MAYACHAINMSGSEND.fields_by_name['address_type'].enum_type = types__pb2._OUTPUTADDRESSTYPE
DESCRIPTOR.message_types_by_name['MayachainGetAddress'] = _MAYACHAINGETADDRESS
DESCRIPTOR.message_types_by_name['MayachainAddress'] = _MAYACHAINADDRESS
DESCRIPTOR.message_types_by_name['MayachainSignTx'] = _MAYACHAINSIGNTX
DESCRIPTOR.message_types_by_name['MayachainMsgRequest'] = _MAYACHAINMSGREQUEST
DESCRIPTOR.message_types_by_name['MayachainMsgAck'] = _MAYACHAINMSGACK
DESCRIPTOR.message_types_by_name['MayachainMsgSend'] = _MAYACHAINMSGSEND
DESCRIPTOR.message_types_by_name['MayachainMsgDeposit'] = _MAYACHAINMSGDEPOSIT
DESCRIPTOR.message_types_by_name['MayachainSignedTx'] = _MAYACHAINSIGNEDTX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MayachainGetAddress = _reflection.GeneratedProtocolMessageType('MayachainGetAddress', (_message.Message,), dict(
  DESCRIPTOR = _MAYACHAINGETADDRESS,
  __module__ = 'messages_mayachain_pb2'
  # @@protoc_insertion_point(class_scope:MayachainGetAddress)
  ))
_sym_db.RegisterMessage(MayachainGetAddress)

MayachainAddress = _reflection.GeneratedProtocolMessageType('MayachainAddress', (_message.Message,), dict(
  DESCRIPTOR = _MAYACHAINADDRESS,
  __module__ = 'messages_mayachain_pb2'
  # @@protoc_insertion_point(class_scope:MayachainAddress)
  ))
_sym_db.RegisterMessage(MayachainAddress)

MayachainSignTx = _reflection.GeneratedProtocolMessageType('MayachainSignTx', (_message.Message,), dict(
  DESCRIPTOR = _MAYACHAINSIGNTX,
  __module__ = 'messages_mayachain_pb2'
  # @@protoc_insertion_point(class_scope:MayachainSignTx)
  ))
_sym_db.RegisterMessage(MayachainSignTx)

MayachainMsgRequest = _reflection.GeneratedProtocolMessageType('MayachainMsgRequest', (_message.Message,), dict(
  DESCRIPTOR = _MAYACHAINMSGREQUEST,
  __module__ = 'messages_mayachain_pb2'
  # @@protoc_insertion_point(class_scope:MayachainMsgRequest)
  ))
_sym_db.RegisterMessage(MayachainMsgRequest)

MayachainMsgAck = _reflection.GeneratedProtocolMessageType('MayachainMsgAck', (_message.Message,), dict(
  DESCRIPTOR = _MAYACHAINMSGACK,
  __module__ = 'messages_mayachain_pb2'
  # @@protoc_insertion_point(class_scope:MayachainMsgAck)
  ))
_sym_db.RegisterMessage(MayachainMsgAck)

MayachainMsgSend = _reflection.GeneratedProtocolMessageType('MayachainMsgSend', (_message.Message,), dict(
  DESCRIPTOR = _MAYACHAINMSGSEND,
  __module__ = 'messages_mayachain_pb2'
  # @@protoc_insertion_point(class_scope:MayachainMsgSend)
  ))
_sym_db.RegisterMessage(MayachainMsgSend)

MayachainMsgDeposit = _reflection.GeneratedProtocolMessageType('MayachainMsgDeposit', (_message.Message,), dict(
  DESCRIPTOR = _MAYACHAINMSGDEPOSIT,
  __module__ = 'messages_mayachain_pb2'
  # @@protoc_insertion_point(class_scope:MayachainMsgDeposit)
  ))
_sym_db.RegisterMessage(MayachainMsgDeposit)

MayachainSignedTx = _reflection.GeneratedProtocolMessageType('MayachainSignedTx', (_message.Message,), dict(
  DESCRIPTOR = _MAYACHAINSIGNEDTX,
  __module__ = 'messages_mayachain_pb2'
  # @@protoc_insertion_point(class_scope:MayachainSignedTx)
  ))
_sym_db.RegisterMessage(MayachainSignedTx)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032com.keepkey.deviceprotocolB\027KeepKeyMessageMayachain'))
_MAYACHAINSIGNTX.fields_by_name['account_number'].has_options = True
_MAYACHAINSIGNTX.fields_by_name['account_number']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('0\001'))
_MAYACHAINSIGNTX.fields_by_name['sequence'].has_options = True
_MAYACHAINSIGNTX.fields_by_name['sequence']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('0\001'))
_MAYACHAINMSGSEND.fields_by_name['amount'].has_options = True
_MAYACHAINMSGSEND.fields_by_name['amount']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('0\001'))
_MAYACHAINMSGDEPOSIT.fields_by_name['amount'].has_options = True
_MAYACHAINMSGDEPOSIT.fields_by_name['amount']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('0\001'))
# @@protoc_insertion_point(module_scope)
