# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages-ripple.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages-ripple.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x15messages-ripple.proto\";\n\x10RippleGetAddress\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x14\n\x0cshow_display\x18\x02 \x01(\x08\" \n\rRippleAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\x8e\x01\n\x0cRippleSignTx\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x0b\n\x03\x66\x65\x65\x18\x02 \x01(\x04\x12\r\n\x05\x66lags\x18\x03 \x01(\r\x12\x10\n\x08sequence\x18\x04 \x01(\r\x12\x1c\n\x14last_ledger_sequence\x18\x05 \x01(\r\x12\x1f\n\x07payment\x18\x06 \x01(\x0b\x32\x0e.RipplePayment\"M\n\rRipplePayment\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x04\x12\x13\n\x0b\x64\x65stination\x18\x02 \x01(\t\x12\x17\n\x0f\x64\x65stination_tag\x18\x03 \x01(\r\":\n\x0eRippleSignedTx\x12\x11\n\tsignature\x18\x01 \x01(\x0c\x12\x15\n\rserialized_tx\x18\x02 \x01(\x0c\x42;\n#com.shapeshift.keepkey.lib.protobufB\x14KeepKeyMessageRipple')
)




_RIPPLEGETADDRESS = _descriptor.Descriptor(
  name='RippleGetAddress',
  full_name='RippleGetAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address_n', full_name='RippleGetAddress.address_n', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='show_display', full_name='RippleGetAddress.show_display', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=84,
)


_RIPPLEADDRESS = _descriptor.Descriptor(
  name='RippleAddress',
  full_name='RippleAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='RippleAddress.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=118,
)


_RIPPLESIGNTX = _descriptor.Descriptor(
  name='RippleSignTx',
  full_name='RippleSignTx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address_n', full_name='RippleSignTx.address_n', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fee', full_name='RippleSignTx.fee', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flags', full_name='RippleSignTx.flags', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='RippleSignTx.sequence', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_ledger_sequence', full_name='RippleSignTx.last_ledger_sequence', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payment', full_name='RippleSignTx.payment', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=263,
)


_RIPPLEPAYMENT = _descriptor.Descriptor(
  name='RipplePayment',
  full_name='RipplePayment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='RipplePayment.amount', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination', full_name='RipplePayment.destination', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination_tag', full_name='RipplePayment.destination_tag', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=342,
)


_RIPPLESIGNEDTX = _descriptor.Descriptor(
  name='RippleSignedTx',
  full_name='RippleSignedTx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signature', full_name='RippleSignedTx.signature', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serialized_tx', full_name='RippleSignedTx.serialized_tx', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=402,
)

_RIPPLESIGNTX.fields_by_name['payment'].message_type = _RIPPLEPAYMENT
DESCRIPTOR.message_types_by_name['RippleGetAddress'] = _RIPPLEGETADDRESS
DESCRIPTOR.message_types_by_name['RippleAddress'] = _RIPPLEADDRESS
DESCRIPTOR.message_types_by_name['RippleSignTx'] = _RIPPLESIGNTX
DESCRIPTOR.message_types_by_name['RipplePayment'] = _RIPPLEPAYMENT
DESCRIPTOR.message_types_by_name['RippleSignedTx'] = _RIPPLESIGNEDTX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RippleGetAddress = _reflection.GeneratedProtocolMessageType('RippleGetAddress', (_message.Message,), dict(
  DESCRIPTOR = _RIPPLEGETADDRESS,
  __module__ = 'messages_ripple_pb2'
  # @@protoc_insertion_point(class_scope:RippleGetAddress)
  ))
_sym_db.RegisterMessage(RippleGetAddress)

RippleAddress = _reflection.GeneratedProtocolMessageType('RippleAddress', (_message.Message,), dict(
  DESCRIPTOR = _RIPPLEADDRESS,
  __module__ = 'messages_ripple_pb2'
  # @@protoc_insertion_point(class_scope:RippleAddress)
  ))
_sym_db.RegisterMessage(RippleAddress)

RippleSignTx = _reflection.GeneratedProtocolMessageType('RippleSignTx', (_message.Message,), dict(
  DESCRIPTOR = _RIPPLESIGNTX,
  __module__ = 'messages_ripple_pb2'
  # @@protoc_insertion_point(class_scope:RippleSignTx)
  ))
_sym_db.RegisterMessage(RippleSignTx)

RipplePayment = _reflection.GeneratedProtocolMessageType('RipplePayment', (_message.Message,), dict(
  DESCRIPTOR = _RIPPLEPAYMENT,
  __module__ = 'messages_ripple_pb2'
  # @@protoc_insertion_point(class_scope:RipplePayment)
  ))
_sym_db.RegisterMessage(RipplePayment)

RippleSignedTx = _reflection.GeneratedProtocolMessageType('RippleSignedTx', (_message.Message,), dict(
  DESCRIPTOR = _RIPPLESIGNEDTX,
  __module__ = 'messages_ripple_pb2'
  # @@protoc_insertion_point(class_scope:RippleSignedTx)
  ))
_sym_db.RegisterMessage(RippleSignedTx)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.shapeshift.keepkey.lib.protobufB\024KeepKeyMessageRipple'))
# @@protoc_insertion_point(module_scope)
