# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages-solana.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15messages-solana.proto\"V\n\x10SolanaGetAddress\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x19\n\tcoin_name\x18\x02 \x01(\t:\x06Solana\x12\x14\n\x0cshow_display\x18\x03 \x01(\x08\" \n\rSolanaAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"k\n\x0fSolanaTokenInfo\x12\x0c\n\x04mint\x18\x01 \x01(\x0c\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x10\n\x08\x64\x65\x63imals\x18\x03 \x01(\r\x12\x11\n\tsignature\x18\x04 \x01(\x0c\x12\x15\n\rsigner_key_id\x18\x05 \x01(\r\"\xae\x02\n\x0cSolanaSignTx\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x19\n\tcoin_name\x18\x02 \x01(\t:\x06Solana\x12\x0e\n\x06raw_tx\x18\x03 \x01(\x0c\x12$\n\ntoken_info\x18\x04 \x03(\x0b\x32\x10.SolanaTokenInfo\x12\x13\n\x0blut_account\x18\x05 \x03(\x0c\x12\x15\n\rlut_signature\x18\x06 \x01(\x0c\x12\x19\n\x11lut_signer_key_id\x18\x07 \x01(\r\x12\x16\n\x0eschema_payload\x18\t \x01(\x0c\x12\x18\n\x10schema_signature\x18\n \x01(\x0c\x12\x1c\n\x14schema_signer_key_id\x18\x0b \x01(\r\x12\x1d\n\x15token_recipient_owner\x18\x0c \x03(\x0cJ\x04\x08\x08\x10\t\"#\n\x0eSolanaSignedTx\x12\x11\n\tsignature\x18\x01 \x01(\x0c\"h\n\x11SolanaSignMessage\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x19\n\tcoin_name\x18\x02 \x01(\t:\x06Solana\x12\x0f\n\x07message\x18\x03 \x01(\x0c\x12\x14\n\x0cshow_display\x18\x04 \x01(\x08\"?\n\x16SolanaMessageSignature\x12\x12\n\npublic_key\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\"\x9c\x01\n\x19SolanaSignOffchainMessage\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x19\n\tcoin_name\x18\x02 \x01(\t:\x06Solana\x12\x12\n\x07version\x18\x03 \x01(\r:\x01\x30\x12\x16\n\x0emessage_format\x18\x04 \x01(\r\x12\x0f\n\x07message\x18\x05 \x01(\x0c\x12\x14\n\x0cshow_display\x18\x06 \x01(\x08\"G\n\x1eSolanaOffchainMessageSignature\x12\x12\n\npublic_key\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x42\x32\n\x1a\x63om.keepkey.deviceprotocolB\x14KeepKeyMessageSolana')



_SOLANAGETADDRESS = DESCRIPTOR.message_types_by_name['SolanaGetAddress']
_SOLANAADDRESS = DESCRIPTOR.message_types_by_name['SolanaAddress']
_SOLANATOKENINFO = DESCRIPTOR.message_types_by_name['SolanaTokenInfo']
_SOLANASIGNTX = DESCRIPTOR.message_types_by_name['SolanaSignTx']
_SOLANASIGNEDTX = DESCRIPTOR.message_types_by_name['SolanaSignedTx']
_SOLANASIGNMESSAGE = DESCRIPTOR.message_types_by_name['SolanaSignMessage']
_SOLANAMESSAGESIGNATURE = DESCRIPTOR.message_types_by_name['SolanaMessageSignature']
_SOLANASIGNOFFCHAINMESSAGE = DESCRIPTOR.message_types_by_name['SolanaSignOffchainMessage']
_SOLANAOFFCHAINMESSAGESIGNATURE = DESCRIPTOR.message_types_by_name['SolanaOffchainMessageSignature']
SolanaGetAddress = _reflection.GeneratedProtocolMessageType('SolanaGetAddress', (_message.Message,), {
  'DESCRIPTOR' : _SOLANAGETADDRESS,
  '__module__' : 'messages_solana_pb2'
  # @@protoc_insertion_point(class_scope:SolanaGetAddress)
  })
_sym_db.RegisterMessage(SolanaGetAddress)

SolanaAddress = _reflection.GeneratedProtocolMessageType('SolanaAddress', (_message.Message,), {
  'DESCRIPTOR' : _SOLANAADDRESS,
  '__module__' : 'messages_solana_pb2'
  # @@protoc_insertion_point(class_scope:SolanaAddress)
  })
_sym_db.RegisterMessage(SolanaAddress)

SolanaTokenInfo = _reflection.GeneratedProtocolMessageType('SolanaTokenInfo', (_message.Message,), {
  'DESCRIPTOR' : _SOLANATOKENINFO,
  '__module__' : 'messages_solana_pb2'
  # @@protoc_insertion_point(class_scope:SolanaTokenInfo)
  })
_sym_db.RegisterMessage(SolanaTokenInfo)

SolanaSignTx = _reflection.GeneratedProtocolMessageType('SolanaSignTx', (_message.Message,), {
  'DESCRIPTOR' : _SOLANASIGNTX,
  '__module__' : 'messages_solana_pb2'
  # @@protoc_insertion_point(class_scope:SolanaSignTx)
  })
_sym_db.RegisterMessage(SolanaSignTx)

SolanaSignedTx = _reflection.GeneratedProtocolMessageType('SolanaSignedTx', (_message.Message,), {
  'DESCRIPTOR' : _SOLANASIGNEDTX,
  '__module__' : 'messages_solana_pb2'
  # @@protoc_insertion_point(class_scope:SolanaSignedTx)
  })
_sym_db.RegisterMessage(SolanaSignedTx)

SolanaSignMessage = _reflection.GeneratedProtocolMessageType('SolanaSignMessage', (_message.Message,), {
  'DESCRIPTOR' : _SOLANASIGNMESSAGE,
  '__module__' : 'messages_solana_pb2'
  # @@protoc_insertion_point(class_scope:SolanaSignMessage)
  })
_sym_db.RegisterMessage(SolanaSignMessage)

SolanaMessageSignature = _reflection.GeneratedProtocolMessageType('SolanaMessageSignature', (_message.Message,), {
  'DESCRIPTOR' : _SOLANAMESSAGESIGNATURE,
  '__module__' : 'messages_solana_pb2'
  # @@protoc_insertion_point(class_scope:SolanaMessageSignature)
  })
_sym_db.RegisterMessage(SolanaMessageSignature)

SolanaSignOffchainMessage = _reflection.GeneratedProtocolMessageType('SolanaSignOffchainMessage', (_message.Message,), {
  'DESCRIPTOR' : _SOLANASIGNOFFCHAINMESSAGE,
  '__module__' : 'messages_solana_pb2'
  # @@protoc_insertion_point(class_scope:SolanaSignOffchainMessage)
  })
_sym_db.RegisterMessage(SolanaSignOffchainMessage)

SolanaOffchainMessageSignature = _reflection.GeneratedProtocolMessageType('SolanaOffchainMessageSignature', (_message.Message,), {
  'DESCRIPTOR' : _SOLANAOFFCHAINMESSAGESIGNATURE,
  '__module__' : 'messages_solana_pb2'
  # @@protoc_insertion_point(class_scope:SolanaOffchainMessageSignature)
  })
_sym_db.RegisterMessage(SolanaOffchainMessageSignature)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.keepkey.deviceprotocolB\024KeepKeyMessageSolana'
  _SOLANAGETADDRESS._serialized_start=25
  _SOLANAGETADDRESS._serialized_end=111
  _SOLANAADDRESS._serialized_start=113
  _SOLANAADDRESS._serialized_end=145
  _SOLANATOKENINFO._serialized_start=147
  _SOLANATOKENINFO._serialized_end=254
  _SOLANASIGNTX._serialized_start=257
  _SOLANASIGNTX._serialized_end=559
  _SOLANASIGNEDTX._serialized_start=561
  _SOLANASIGNEDTX._serialized_end=596
  _SOLANASIGNMESSAGE._serialized_start=598
  _SOLANASIGNMESSAGE._serialized_end=702
  _SOLANAMESSAGESIGNATURE._serialized_start=704
  _SOLANAMESSAGESIGNATURE._serialized_end=767
  _SOLANASIGNOFFCHAINMESSAGE._serialized_start=770
  _SOLANASIGNOFFCHAINMESSAGE._serialized_end=926
  _SOLANAOFFCHAINMESSAGESIGNATURE._serialized_start=928
  _SOLANAOFFCHAINMESSAGESIGNATURE._serialized_end=999
# @@protoc_insertion_point(module_scope)
