# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages-ton.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages-ton.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12messages-ton.proto\"\x98\x01\n\rTonGetAddress\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x16\n\tcoin_name\x18\x02 \x01(\t:\x03Ton\x12\x14\n\x0cshow_display\x18\x03 \x01(\x08\x12\x18\n\nbounceable\x18\x04 \x01(\x08:\x04true\x12\x16\n\x07testnet\x18\x05 \x01(\x08:\x05\x66\x61lse\x12\x14\n\tworkchain\x18\x06 \x01(\x11:\x01\x30\"2\n\nTonAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x13\n\x0braw_address\x18\x02 \x01(\t\"\xa2\x01\n\tTonSignTx\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x16\n\tcoin_name\x18\x02 \x01(\t:\x03Ton\x12\x0e\n\x06raw_tx\x18\x03 \x01(\x0c\x12\x11\n\texpire_at\x18\x04 \x01(\r\x12\r\n\x05seqno\x18\x05 \x01(\r\x12\x14\n\tworkchain\x18\x06 \x01(\x11:\x01\x30\x12\x12\n\nto_address\x18\x07 \x01(\t\x12\x0e\n\x06\x61mount\x18\x08 \x01(\x04\" \n\x0bTonSignedTx\x12\x11\n\tsignature\x18\x01 \x01(\x0c\x42/\n\x1a\x63om.keepkey.deviceprotocolB\x11KeepKeyMessageTon')
)




_TONGETADDRESS = _descriptor.Descriptor(
  name='TonGetAddress',
  full_name='TonGetAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address_n', full_name='TonGetAddress.address_n', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coin_name', full_name='TonGetAddress.coin_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("Ton").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='show_display', full_name='TonGetAddress.show_display', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bounceable', full_name='TonGetAddress.bounceable', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='testnet', full_name='TonGetAddress.testnet', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workchain', full_name='TonGetAddress.workchain', index=5,
      number=6, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=175,
)


_TONADDRESS = _descriptor.Descriptor(
  name='TonAddress',
  full_name='TonAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='TonAddress.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_address', full_name='TonAddress.raw_address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=227,
)


_TONSIGNTX = _descriptor.Descriptor(
  name='TonSignTx',
  full_name='TonSignTx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address_n', full_name='TonSignTx.address_n', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='coin_name', full_name='TonSignTx.coin_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("Ton").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_tx', full_name='TonSignTx.raw_tx', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expire_at', full_name='TonSignTx.expire_at', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqno', full_name='TonSignTx.seqno', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workchain', full_name='TonSignTx.workchain', index=5,
      number=6, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_address', full_name='TonSignTx.to_address', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='TonSignTx.amount', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=230,
  serialized_end=392,
)


_TONSIGNEDTX = _descriptor.Descriptor(
  name='TonSignedTx',
  full_name='TonSignedTx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='signature', full_name='TonSignedTx.signature', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=426,
)

DESCRIPTOR.message_types_by_name['TonGetAddress'] = _TONGETADDRESS
DESCRIPTOR.message_types_by_name['TonAddress'] = _TONADDRESS
DESCRIPTOR.message_types_by_name['TonSignTx'] = _TONSIGNTX
DESCRIPTOR.message_types_by_name['TonSignedTx'] = _TONSIGNEDTX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TonGetAddress = _reflection.GeneratedProtocolMessageType('TonGetAddress', (_message.Message,), dict(
  DESCRIPTOR = _TONGETADDRESS,
  __module__ = 'messages_ton_pb2'
  # @@protoc_insertion_point(class_scope:TonGetAddress)
  ))
_sym_db.RegisterMessage(TonGetAddress)

TonAddress = _reflection.GeneratedProtocolMessageType('TonAddress', (_message.Message,), dict(
  DESCRIPTOR = _TONADDRESS,
  __module__ = 'messages_ton_pb2'
  # @@protoc_insertion_point(class_scope:TonAddress)
  ))
_sym_db.RegisterMessage(TonAddress)

TonSignTx = _reflection.GeneratedProtocolMessageType('TonSignTx', (_message.Message,), dict(
  DESCRIPTOR = _TONSIGNTX,
  __module__ = 'messages_ton_pb2'
  # @@protoc_insertion_point(class_scope:TonSignTx)
  ))
_sym_db.RegisterMessage(TonSignTx)

TonSignedTx = _reflection.GeneratedProtocolMessageType('TonSignedTx', (_message.Message,), dict(
  DESCRIPTOR = _TONSIGNEDTX,
  __module__ = 'messages_ton_pb2'
  # @@protoc_insertion_point(class_scope:TonSignedTx)
  ))
_sym_db.RegisterMessage(TonSignedTx)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032com.keepkey.deviceprotocolB\021KeepKeyMessageTon'))
# @@protoc_insertion_point(module_scope)
