# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages-tendermint.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import types_pb2 as types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages-tendermint.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x19messages-tendermint.proto\x1a\x0btypes.proto\"|\n\x14TendermintGetAddress\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x14\n\x0cshow_display\x18\x02 \x01(\x08\x12\x0f\n\x07testnet\x18\x03 \x01(\x08\x12\x16\n\x0e\x61\x64\x64ress_prefix\x18\x04 \x01(\t\x12\x12\n\nchain_name\x18\x05 \x01(\t\"$\n\x11TendermintAddress\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\x8e\x02\n\x10TendermintSignTx\x12\x11\n\taddress_n\x18\x01 \x03(\r\x12\x1a\n\x0e\x61\x63\x63ount_number\x18\x02 \x01(\x04\x42\x02\x30\x01\x12\x10\n\x08\x63hain_id\x18\x03 \x01(\t\x12\x12\n\nfee_amount\x18\x04 \x01(\r\x12\x0b\n\x03gas\x18\x05 \x01(\r\x12\x0c\n\x04memo\x18\x06 \x01(\t\x12\x14\n\x08sequence\x18\x07 \x01(\x04\x42\x02\x30\x01\x12\x11\n\tmsg_count\x18\x08 \x01(\r\x12\x0f\n\x07testnet\x18\t \x01(\x08\x12\r\n\x05\x64\x65nom\x18\n \x01(\t\x12\x10\n\x08\x64\x65\x63imals\x18\x0b \x01(\x04\x12\x12\n\nchain_name\x18\x0c \x01(\t\x12\x1b\n\x13message_type_prefix\x18\r \x01(\t\"\x16\n\x14TendermintMsgRequest\"t\n\x10TendermintMsgAck\x12 \n\x04send\x18\x01 \x01(\x0b\x32\x12.TendermintMsgSend\x12\r\n\x05\x64\x65nom\x18\x02 \x01(\t\x12\x12\n\nchain_name\x18\x03 \x01(\t\x12\x1b\n\x13message_type_prefix\x18\x04 \x01(\t\"\xa1\x01\n\x11TendermintMsgSend\x12\x14\n\x0c\x66rom_address\x18\x06 \x01(\t\x12\x12\n\nto_address\x18\x07 \x01(\t\x12\x12\n\x06\x61mount\x18\x08 \x01(\x04\x42\x02\x30\x01\x12(\n\x0c\x61\x64\x64ress_type\x18\t \x01(\x0e\x32\x12.OutputAddressType\x12$\n\rexchange_type\x18\n \x01(\x0b\x32\r.ExchangeType\";\n\x12TendermintSignedTx\x12\x12\n\npublic_key\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\x42?\n#com.shapeshift.keepkey.lib.protobufB\x18KeepKeyMessageTendermint')
  ,
  dependencies=[types__pb2.DESCRIPTOR,])




_TENDERMINTGETADDRESS = _descriptor.Descriptor(
  name='TendermintGetAddress',
  full_name='TendermintGetAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address_n', full_name='TendermintGetAddress.address_n', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='show_display', full_name='TendermintGetAddress.show_display', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='testnet', full_name='TendermintGetAddress.testnet', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address_prefix', full_name='TendermintGetAddress.address_prefix', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chain_name', full_name='TendermintGetAddress.chain_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=166,
)


_TENDERMINTADDRESS = _descriptor.Descriptor(
  name='TendermintAddress',
  full_name='TendermintAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='TendermintAddress.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=204,
)


_TENDERMINTSIGNTX = _descriptor.Descriptor(
  name='TendermintSignTx',
  full_name='TendermintSignTx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address_n', full_name='TendermintSignTx.address_n', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account_number', full_name='TendermintSignTx.account_number', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('0\001')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chain_id', full_name='TendermintSignTx.chain_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fee_amount', full_name='TendermintSignTx.fee_amount', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gas', full_name='TendermintSignTx.gas', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memo', full_name='TendermintSignTx.memo', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sequence', full_name='TendermintSignTx.sequence', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('0\001')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_count', full_name='TendermintSignTx.msg_count', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='testnet', full_name='TendermintSignTx.testnet', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='denom', full_name='TendermintSignTx.denom', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='decimals', full_name='TendermintSignTx.decimals', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chain_name', full_name='TendermintSignTx.chain_name', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_type_prefix', full_name='TendermintSignTx.message_type_prefix', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=477,
)


_TENDERMINTMSGREQUEST = _descriptor.Descriptor(
  name='TendermintMsgRequest',
  full_name='TendermintMsgRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=479,
  serialized_end=501,
)


_TENDERMINTMSGACK = _descriptor.Descriptor(
  name='TendermintMsgAck',
  full_name='TendermintMsgAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='send', full_name='TendermintMsgAck.send', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='denom', full_name='TendermintMsgAck.denom', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='chain_name', full_name='TendermintMsgAck.chain_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_type_prefix', full_name='TendermintMsgAck.message_type_prefix', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=619,
)


_TENDERMINTMSGSEND = _descriptor.Descriptor(
  name='TendermintMsgSend',
  full_name='TendermintMsgSend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from_address', full_name='TendermintMsgSend.from_address', index=0,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to_address', full_name='TendermintMsgSend.to_address', index=1,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='TendermintMsgSend.amount', index=2,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('0\001')), file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address_type', full_name='TendermintMsgSend.address_type', index=3,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exchange_type', full_name='TendermintMsgSend.exchange_type', index=4,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=622,
  serialized_end=783,
)


_TENDERMINTSIGNEDTX = _descriptor.Descriptor(
  name='TendermintSignedTx',
  full_name='TendermintSignedTx',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='public_key', full_name='TendermintSignedTx.public_key', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signature', full_name='TendermintSignedTx.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=785,
  serialized_end=844,
)

_TENDERMINTMSGACK.fields_by_name['send'].message_type = _TENDERMINTMSGSEND
_TENDERMINTMSGSEND.fields_by_name['address_type'].enum_type = types__pb2._OUTPUTADDRESSTYPE
_TENDERMINTMSGSEND.fields_by_name['exchange_type'].message_type = types__pb2._EXCHANGETYPE
DESCRIPTOR.message_types_by_name['TendermintGetAddress'] = _TENDERMINTGETADDRESS
DESCRIPTOR.message_types_by_name['TendermintAddress'] = _TENDERMINTADDRESS
DESCRIPTOR.message_types_by_name['TendermintSignTx'] = _TENDERMINTSIGNTX
DESCRIPTOR.message_types_by_name['TendermintMsgRequest'] = _TENDERMINTMSGREQUEST
DESCRIPTOR.message_types_by_name['TendermintMsgAck'] = _TENDERMINTMSGACK
DESCRIPTOR.message_types_by_name['TendermintMsgSend'] = _TENDERMINTMSGSEND
DESCRIPTOR.message_types_by_name['TendermintSignedTx'] = _TENDERMINTSIGNEDTX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TendermintGetAddress = _reflection.GeneratedProtocolMessageType('TendermintGetAddress', (_message.Message,), dict(
  DESCRIPTOR = _TENDERMINTGETADDRESS,
  __module__ = 'messages_tendermint_pb2'
  # @@protoc_insertion_point(class_scope:TendermintGetAddress)
  ))
_sym_db.RegisterMessage(TendermintGetAddress)

TendermintAddress = _reflection.GeneratedProtocolMessageType('TendermintAddress', (_message.Message,), dict(
  DESCRIPTOR = _TENDERMINTADDRESS,
  __module__ = 'messages_tendermint_pb2'
  # @@protoc_insertion_point(class_scope:TendermintAddress)
  ))
_sym_db.RegisterMessage(TendermintAddress)

TendermintSignTx = _reflection.GeneratedProtocolMessageType('TendermintSignTx', (_message.Message,), dict(
  DESCRIPTOR = _TENDERMINTSIGNTX,
  __module__ = 'messages_tendermint_pb2'
  # @@protoc_insertion_point(class_scope:TendermintSignTx)
  ))
_sym_db.RegisterMessage(TendermintSignTx)

TendermintMsgRequest = _reflection.GeneratedProtocolMessageType('TendermintMsgRequest', (_message.Message,), dict(
  DESCRIPTOR = _TENDERMINTMSGREQUEST,
  __module__ = 'messages_tendermint_pb2'
  # @@protoc_insertion_point(class_scope:TendermintMsgRequest)
  ))
_sym_db.RegisterMessage(TendermintMsgRequest)

TendermintMsgAck = _reflection.GeneratedProtocolMessageType('TendermintMsgAck', (_message.Message,), dict(
  DESCRIPTOR = _TENDERMINTMSGACK,
  __module__ = 'messages_tendermint_pb2'
  # @@protoc_insertion_point(class_scope:TendermintMsgAck)
  ))
_sym_db.RegisterMessage(TendermintMsgAck)

TendermintMsgSend = _reflection.GeneratedProtocolMessageType('TendermintMsgSend', (_message.Message,), dict(
  DESCRIPTOR = _TENDERMINTMSGSEND,
  __module__ = 'messages_tendermint_pb2'
  # @@protoc_insertion_point(class_scope:TendermintMsgSend)
  ))
_sym_db.RegisterMessage(TendermintMsgSend)

TendermintSignedTx = _reflection.GeneratedProtocolMessageType('TendermintSignedTx', (_message.Message,), dict(
  DESCRIPTOR = _TENDERMINTSIGNEDTX,
  __module__ = 'messages_tendermint_pb2'
  # @@protoc_insertion_point(class_scope:TendermintSignedTx)
  ))
_sym_db.RegisterMessage(TendermintSignedTx)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n#com.shapeshift.keepkey.lib.protobufB\030KeepKeyMessageTendermint'))
_TENDERMINTSIGNTX.fields_by_name['account_number'].has_options = True
_TENDERMINTSIGNTX.fields_by_name['account_number']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('0\001'))
_TENDERMINTSIGNTX.fields_by_name['sequence'].has_options = True
_TENDERMINTSIGNTX.fields_by_name['sequence']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('0\001'))
_TENDERMINTMSGSEND.fields_by_name['amount'].has_options = True
_TENDERMINTMSGSEND.fields_by_name['amount']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('0\001'))
# @@protoc_insertion_point(module_scope)
